### ISSUE TITLE
SQL ERROR [ mysqli ] (bug in v1.0.6)

### ISSUE THREAD

**Issue by 3D-I** [rmcgirr83/activity24hours#12]
> Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'qi_321_vanilla.s.session_viewonline' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [1055]

**Comment by 3D-I** [comment]
Changing the line 191 in the listener to
`'GROUP_BY'	=> 'u.user_id, s.session_viewonline',`
seems to have fixed the issue, but's a virgin board and I don't know the behavior of your code yet.

**Comment by 3D-I** [comment]
BTW, while reading the support topics in the contribution's area I noticed this fix has been already taken, wondering why isn't in the code yet..

**Comment by rmcgirr83** [comment]
https://github.com/rmcgirr83/phpBB-3.1-activity24hours/commit/f68b7d588e5d80c13132768c881e86e6aa2eae81
