### ISSUE TITLE
Small glitch on "not users active"

### ISSUE THREAD

**Issue by 3D-I** [rmcgirr83/activity24hours#13]
http://prntscr.com/hxubm8

> In total there were 0 users :: 0 registered, 0 hidden and 0 guests active over the last 24 **hoursNo** registered users 

In the template event simply add a <br>
`{% if not USERS_ACTIVE %}<br>{{ lang('NO_ONLINE_USERS') }}`

**Comment by rmcgirr83** [comment]
Make a PR please

**Comment by 3D-I** [comment]
> remote: Permission to rmcgirr83/phpBB-3.1-activity24hours.git denied to 3D-I.

PR is ready though. This repo's settings?

**Comment by rmcgirr83** [comment]
Not sure what it is you are asking

**Comment by 3D-I** [comment]
Seems a permission error on your side Rich, check the repo settings pls.

> git.exe push --progress "origin" Issue#13

> remote: Permission to rmcgirr83/phpBB-3.1-activity24hours.git denied to 3D-I.
> fatal: unable to access 'https://github.com/rmcgirr83/phpBB-3.1-activity24hours.git/': The requested URL returned error: 403

**Comment by rmcgirr83** [comment]
You don't have push permissions to my repo.  You have to make a PR using a commit from your fork of this extension.
