### ISSUE TITLE
Extension is not working on theme style other than prosilver

### ISSUE THREAD

**Issue by mcclayn** [rmcgirr83/activity24hours#3]
![clip2net_160406180916](https://cloud.githubusercontent.com/assets/18310018/14321634/b3d55e9e-fc22-11e5-98e9-d89802703bab.png)

Hello there, I see that in your extension, in activities for the last 24 hours, it says there were certain number of registered users. However, on my forum, there was definately no 57 new user registrations. Only 1 user has registered. Where this info comes from?

**Comment by rmcgirr83** [comment]
Not sure what that has to do with the title of this topic? That information is gotten from the users table and is cached https://github.com/RMcGirr83/phpBB-3.1-activity24hours/blob/master/event/listener.php#L202-L211

In the future please post an issue as per your title.  Not something completely and totally different.
