### ISSUE TITLE
Bots still shown even with Hide Bots extension installed.

### ISSUE THREAD

**Issue by Sophist-UK** [rmcgirr83/activity24hours#6]

**Comment by Sophist-UK** [comment]
It appears that there may have been a commit a few days ago to fix this that has not yet made it to the official version. I will try to download from here and see if it works.

**Comment by Sophist-UK** [comment]
I have installed from GH and I still have bots being shown even with Hide Bots installed.

See also #7.

**Comment by rmcgirr83** [comment]
If you are the admin of the forum you will always see the bots when logged in.

**Comment by Sophist-UK** [comment]
Ah.

**Comment by rmcgirr83** [comment]
Sorry thought it was the hide bots extension, where are you seeing the bots in this extension?
