### ISSUE TITLE
Screwy html for online users

### ISSUE THREAD

**Issue by Sophist-UK** [rmcgirr83/activity24hours#7]
I have downloaded the extension from here and I am getting the following html:

```
<span title="<span title="|28 Sep 2017|, 11:07">11 hours ago</span>"><span style="color: #9E8DA7;" class="username-coloured">Google [Bot]</span></span>,  
<span title="<span title="|28 Sep 2017|, 18:48">3 hours ago</span>"><a href="./memberlist.php?mode=viewprofile&amp;u=48" style="color: #AA0000;" class="username-coloured">Imshi</a></span>,  
<span title="<span title="|28 Sep 2017|, 22:28">13 minutes ago</span>"><a href="./memberlist.php?mode=viewprofile&amp;u=2" class="username"><em>rkadmin</em></a></span>`
```

As you can see we have extra span tags inserted inside other span tags. I have no idea why - the code that generates these tags looks ok. So I am guessing it is a conflict with another extension, but no idea what that might be.

**Comment by Galixte** [comment]
Hi @Sophist-UK,

a very easy way, disable all your extensions except this (24 hours), activate one of them disabled, make some tests, if it's not this one, activate another one, make some tests, if it's not this extension, activate another extension… etc… etc…

**Comment by Sophist-UK** [comment]
Ok - I'll try that tomorrow.

**Comment by Sophist-UK** [comment]
Actually I just did it and it is the [Relative Dates extension](https://www.phpbb.com/customise/db/extension/relative_dates/) which states:

> Absolute date on mouseover of relative date 

Which makes a whole lot of sense.

**Comment by Sophist-UK** [comment]
I will try to code a fix in the next day or two.

**Comment by Sophist-UK** [comment]
Closing in favour of PR.
