### ISSUE TITLE
Global group settings "can hide online-status" not recognized

### ISSUE THREAD

**Issue by bug-i** [rmcgirr83/activity24hours#9]
When I set in the ACP for all groups "can hide online status" to no/never it does not have an effect on 24h activity stats. Which means that all user that have decided in their user-settings to hide themselvesare still hidden in the 24 activity stat (but not on "who is online").

As the settings for the groups in the ACP should overrule the usersettings this should be reflected in 24h activity stats as well

**Comment by rmcgirr83** [comment]
The queries are cached for every 5 minutes.  Purge the cache if you want immediate changes.

**Comment by bug-i** [comment]
I made the changes some days ago, so its not a question of caching

**Comment by rmcgirr83** [comment]
Try changing this line

https://github.com/rmcgirr83/phpBB-3.1-activity24hours/blob/master/event/listener.php#L108

to this

`if (!$row['session_viewonline'])`

remember to purge the cache as the data is cached for five minutes.

**Comment by Sophist-UK** [comment]
If this extension is going to display similarly to native phpbb (which IMO it should) then the above change should be a permanent fix to match /viewonline.php line 202.

**Comment by Galixte** [comment]
Hi @rmcgirr83 some users on phpBB-fr report that this issue is still present in 1.0.7 version. Could you take a look, please?

**Comment by rmcgirr83** [comment]
https://github.com/rmcgirr83/phpBB-3.1-activity24hours/pull/16
